project_name: "RAG_Benchmark"

# ===========修改配置================
dataset_name: "HotpotQA"

adapter:
  module: "src.adapters.hotpotqa_adapter"
  class_name: "HotpotQAAdapter"

store:
  type: "pageindex"
  pageindex_config_path: "ov_test/pageindex.conf"

execution:
  max_workers: 10
  ingest_workers: 4
  retrieval_topk: 5
  max_queries: null
# ==================================

paths:
  raw_data: "Data/{dataset_name}/hotpot_qa_100.json"
  doc_output_dir: "Data/{dataset_name}/pageindex/processed_docs"
  vector_store: "Data/{dataset_name}/pageindex/store_index"
  output_dir: "Output/{dataset_name}/pageindex_global/experiment_0001"
  log_file: "Output/{dataset_name}/pageindex_global/experiment_0001/benchmark.log"

llm:
  model: "${LLM_MODEL}"
  temperature: 0
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"
