[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kohaku-rag"
version = "0.0.1"
description = "Simple RAG system for WattBot 2025"
authors = [
    { name = "Shih-Ying Yeh(KohakuBlueLeaf)", email = "apolloyeh0123@gmail.com" },
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops",
    "numpy>=2.3",
    "torch",
    "transformers",
    "pypdf>=6.2.0",
    "pymupdf>=1.25.0",
    "httpx>=0.27.0",
    "kohakuvault>=0.7.1",
    "openai>=2.8.0",
    "Pillow>=12.0.0",
    "openrouter",
    "torchvision",
    "peft",
    "matplotlib",
    "scikit-learn",
    "umap-learn",
]
urls = { "Homepage" = "https://github.com/KohakuBlueleaf/KohakuRAG" }

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.setuptools]
package-dir = {"" = "src"}
