project_name: "RAG_Benchmark"

# ===========修改配置================
dataset_name: "ClapNQ"

adapter:
  module: "src.adapters.clapnq_adapter"
  class_name: "ClapNQAdapter"

execution:
  max_workers: 10
  ingest_workers: 5
  retrieval_topk: 5
  max_queries: null
# ==================================

paths:
  raw_data: "Data/clapnq-main"
  doc_output_dir: "Data/clapnq-main/openviking_per_question/processed_docs"
  vector_store: "Data/clapnq-main/openviking_per_question/store_index"
  output_dir: "Output/ClapNQ/openviking_per_question/experiment_0001"
  log_file: "Output/ClapNQ/openviking_per_question/experiment_0001/benchmark.log"

llm:
  model: "${LLM_MODEL}"
  temperature: 0
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"
