
project_name: "RAG_Benchmark"

# ===========修改配置================
dataset_name: "ClapNQ" 

adapter:
  module: "src.adapters.clapnq_adapter"  
  class_name: "ClapNQAdapter"     

execution:
  max_workers: 10      # LLM 生成任务的并发数
  ingest_workers: 1      # 数据入库任务的并发数，提交到ov的并发数
  retrieval_topk: 5
  max_queries: null        # 最大查询数，null表示全部查询
# ==================================  

paths:
  raw_data: "Data/clapnq-main"
  doc_output_dir: "Data/clapnq-main/openviking/processed_docs"
  vector_store: "Data/clapnq-main/openviking/store_index"
  output_dir: "Output/ClapNQ/openviking_global/experiment_0001"
  log_file: "Output/ClapNQ/openviking_global/experiment_0001/benchmark.log"


llm:
  model: "${LLM_MODEL}"
  temperature: 0
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"

